# Generated by Django 5.0 on 2023-12-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_number',
            field=models.IntegerField(max_length=16, verbose_name='Numero de tarjeta'),
        ),
    ]
