# Generated by Django 5.0 on 2023-12-14 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request', '0002_alter_paymentinfo_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_cvv',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3), django.core.validators.MaxLengthValidator(limit_value=3)], verbose_name='Clave de tarjeta'),
        ),
    ]
