# Generated by Django 5.0 on 2023-12-14 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_request', '0003_alter_paymentinfo_card_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='comission_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Comisión'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_cvv',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3), django.core.validators.MaxLengthValidator(limit_value=3)], verbose_name='Clave de tarjeta'),
        ),
    ]
